### ISSUE TITLE
HTTP 400 error: Unable to create record: 

### ISSUE THREAD

**Issue by prabapro** [kartik-nighania/whatsapp_with_aws_lambda#3]
Hi @kartik-nighania ,

Thanks for your amazing medium article. I'm getting below error when I'm testing at Lamda. Please assist mate. Thanks.
```
START RequestId: 5315c356-7409-4825-b4e2-8da6fcee3294 Version: $LATEST
HTTP 400 error: Unable to create record: Twilio could not find a Channel with the specified From address: TwilioRestException
Traceback (most recent call last):
  File "/var/task/whatsapp_messaging.py", line 19, in msg_mom_and_dad
    to='whatsapp:' + value,
  File "/var/task/twilio/rest/api/v2010/account/message/__init__.py", line 87, in create
    data=data,
  File "/var/task/twilio/base/version.py", line 209, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to create record: Twilio could not find a Channel with the specified From address

END RequestId: 5315c356-7409-4825-b4e2-8da6fcee3294
REPORT RequestId: 5315c356-7409-4825-b4e2-8da6fcee3294	Duration: 2355.48 ms	Billed Duration: 2400 ms	Memory Size: 128 MB	Max Memory Used: 66 MB	Init Duration: 136.68 ms	
```

**Comment by elhawlir** [comment]
I got the same problem as above. Keeps telling me it can't find 'whatsapp_messaging'

**Comment by sndipn616** [comment]
Getting the same error as well. Anybody found a workaround?
